@startuml

title Извлечение релевантных мыслей (retrieve_relevant_thoughts)

start
:Получение запроса и параметров:
- Текст запроса
- Порог релевантности (threshold)
- Максимальное количество результатов;

if (Есть мысли в памяти?) then (нет)
    :Возврат пустого множества;
    stop
else (да)
endif

:Получение эмбеддингов:
- Эмбеддинг запроса
- Эмбеддинги всех мыслей;

:Расчет косинусного сходства между запросом и мыслями;

:Выбор мыслей выше порога релевантности;

:Создание списка пар (сходство, мысль);

:Сортировка по убыванию сходства;

:Выбор топ-N мыслей (max_results);

:Возврат множества отобранных мыслей;

stop

@enduml 