@startuml

title Рефлексия персонажа (reflect)

start
:Получение недавних событий из памяти;

if (Есть недавние события?) then (нет)
    stop
else (да)
endif

:Формирование промпта для рефлексии:
- Характеристики персонажа
- Недавние события
- Запрос на размышления;

:Генерация рефлексии через LLM;

:Создание узла мысли:
- ID: следующий доступный
- Тип: thought
- Описание: текст рефлексии
- Ключ эмбеддинга: thought
- Важность: 5 (высокая)
- Субъект: имя персонажа
- Предикат: reflects
- Объект: recent events;

:Добавление узла в память;

stop

@enduml 