@startuml

title Обработка полученного ответа (get_answer)

start
:Получение ответа и имени отправителя;

:Создание и сохранение узла чата:
- ID: следующий доступный
- Тип: chat
- Описание: "отправитель: сообщение"
- Важность: 2;

:Увеличение счетчика сообщений;

if (Рефлексия включена?) then (да)
    if (Счетчик >= порога?) then (да)
        :Запуск рефлексии:
        - Получение событий
        - Создание размышления
        - Сброс счетчика;
    endif
endif

stop

@enduml 