@startuml

start

:Инициализация симуляции;
:Создание персон;
:Инициализация матрицы дистанций;

while (Текущий цикл < Максимальное количество циклов?) is (да)
    :Увеличение счетчика циклов;
    
    if (Кратно SHUFFLE_PERIOD?) then (да)
        :Обновление пар для взаимодействия;
    else (нет)
    endif
    
    if (Кратно RUMOR_PERIOD?) then (да)
        :Генерация нового слуха;
    else (нет)
    endif
    
    repeat
        :Взаимодействие пары агентов;
        :Обмен слухами;
    repeat while (Есть еще пары?) is (да) not (нет)
    
    :Пауза между циклами;
endwhile (нет)

:Сохранение статистики;
stop

@enduml 